name: SauceDemo Merge PR Verification

on:
  pull_request:
    branches: [ main, master ]
    types: [ opened, synchronize ]

jobs:
  run-picked-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers (Chỉ cài Firefox)
        run: npx playwright install firefox --with-deps

      - name: Run Login Test on Firefox
        run: npx playwright test login.spec.ts --project "firefox"
